### ISSUE TITLE
Unnecessary rebuilds in build script

### ISSUE THREAD

**Issue by danielocfb** [libbpf/blazesym#91]
I noticed that our benchmark files are repeatedly generated every time we benchmark. Given the size of the artifacts used, that process takes a while. It's also not expected, but it's not clear why exactly that is (it's possible that the dependencies we have cannot properly be expressed in build scripts at all). We should see if that can be fixed so that we only re-generate those files if something changed.

**Comment by d-e-s-o** [comment]
I had a look at this issue. The problem seems to be that the generated files' mtimes are after those of the output that they are compared against to determine staleness. Intuitively, that makes no sense, because it is the build script that emits those outputs to stdout while also generating those files. Hence, the build script's outputs can only be available completely *after* said script has run (that is, after the files have been generated as well).

This behavior seems to be caused by https://github.com/rust-lang/cargo/blob/4a60ff78a5f03e7c9ed2399754efb62c80a8ecc8/src/cargo/core/compiler/fingerprint/mod.rs?L249#L249-L256 and so is fully intentional to the degree I can tell. I haven't dug into why exactly that is (the comments doesn't make it clear to me), but I will say that we are somewhat out of the purview of what build scripts are meant to be used for. E.g., just check https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script

This is not a blocking issue, but it's not great behavior either. One thing I believe we can do is rewind the mtimes of our generated files to a time before the output file's mtime.
